apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJpdGF5a2FsaW5pbnNreSIsCiAgICAgICJwYXNzd29yZCI6ICJTcGlrZWRvZyFxMnciLAogICAgICAiZW1haWwiOiAiaS5rYWxpbmluc2t5QGdtYWlsLmNvbSIsCiAgICAgICJhdXRoIjogImFYUmhlV3RoYkdsdWFXNXphM2s2VTNCcGEyVmtiMmNoY1RKMyIKICAgIH0KICB9Cn0K
