apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: my-app
    namespace: my-namespace
spec:
    project: default
    source:
        repoURL: <repository-url>
        targetRevision: <commit-or-branch>
        path: <path-to-application-files>
    destination:
        server: https://kubernetes.default.svc
        namespace: weatherapp
    syncPolicy:
        automated:
            prune: true
            selfHeal: true