apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: my-app
    namespace: my-namespace
spec:
    project: default
    source:
        repoURL: 'https://github.com/The-LittleTeapot/ArgoCD-Helm.git'
        path: Helm/templates
        targetRevision: HEAD
    destination:
        server: https://kubernetes.default.svc
        namespace: weatherapp
    syncPolicy:
        automated:
            prune: true
            selfHeal: true